### ISSUE TITLE
About the Margins in The about section

### ISSUE THREAD

**Issue by NatanimA** [amon-cofie/Mobile-first-Portfolio#5]
--->Very Responsive 👍🏼 
--->professional ReadMe
..But there is a minor issue with the margins between the description and The logos ,Please Make a margin-left to make it as perfect as the figma design. 👍🏼

**Comment by amon-cofie** [comment]
> --->Very Responsive 👍🏼 --->professional ReadMe ..But there is a minor issue with the margins between the description and The logos ,Please Make a margin-left to make it as perfect as the figma design. 👍🏼

Thanks a lot! Will do well to fix that

**Comment by GraceAbike** [comment]
@amon-cofie You have done a great job continuing the good work 💯

**Comment by amon-cofie** [comment]
> @amon-cofie You have done a great job continuing the good work 💯

Thanks a lot!

**Comment by Fayob** [comment]
You've done the a great job 👍 in this project. I will suggest you fix the mobile background after your break point.

Well done 💯

**Comment by amon-cofie** [comment]
> You've done a great job 👍 in this project. I will suggest you fix the mobile background after your break point.
> 
> Well done 💯

Thanks a lot! I will fix that
