### ISSUE TITLE
Peer-to-peer code review.

### ISSUE THREAD

**Issue by 28919926** [amon-cofie/Mobile-first-Portfolio#8]
You did great work and your code is amazing, especially on the form section where you have used a list on the form .👏👏👍
However, there are a few recommendations we have:

- On the menu icons, you can use material icons instead of images for dry code.
- You may also use margin inline-start, inline-end and margin block-start, and block-end for margin-left, right, bottom and top.

All in all you deed a great work and cheers✔👍

**Comment by amon-cofie** [comment]
Thank you very much. I will make those changes.
